<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/letter-([^/]{1,3})/page-([0-9]+)/(.*)#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2&page_count=\$5&letter=\$6&PAGEN_1=\$7",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/letter-([^/]{1,3})/(.*)#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2&page_count=\$5&letter=\$6",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?view-(\\w*)/sort-(\\w*)-(\\w*)/letter-([^/]{1,3})/page-([0-9]+)/(.*)#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2&letter=\$5&PAGEN_1=\$6",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/page-([0-9]+)/#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2&PAGEN_1=\$6&page_count=\$5",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2&page_count=\$5",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?page_count-([0-9]+)/letter-([^/]{1,3})/(.*)#",
		"RULE" => "SECTION_CODE=\$1&page_count=\$2&letter=\$3",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?letter-([^/]{1,3})/page_count-([0-9]+)/(.*)#",
		"RULE" => "SECTION_CODE=\$1&letter=\$2&page_count=\$3",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/page-([0-9]+)/#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2&PAGEN_1=\$5",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?letter-([^/]{1,3})/page-([0-9]+)/(.*)#",
		"RULE" => "SECTION_CODE=\$1&letter=\$2&PAGEN_1=\$3",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/bestseller/sort-(.*[^-])-(.*)/page-([0-9]+)/(.*)#",
		"RULE" => "\$4&order=\$1&by=\$2&PAGEN_1=\$3&ys_ms_sef=y&tab_block=BESTSELLER",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/sale/sort-(.*[^-])-(.*)/page-([0-9]+)/(.*)#",
		"RULE" => "\$4&order=\$1&by=\$2&PAGEN_1=\$3&ys_ms_sef=y&tab_block=SALE",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/#",
		"RULE" => "SECTION_CODE=\$1&order=\$3&by=\$4&view=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/hit/sort-(.*[^-])-(.*)/page-([0-9]+)/(.*)#",
		"RULE" => "\$4&order=\$1&by=\$2&PAGEN_1=\$3&ys_ms_sef=y&tab_block=HIT",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/new/sort-(.*[^-])-(.*)/page-([0-9]+)/(.*)#",
		"RULE" => "\$4&order=\$1&by=\$2&PAGEN_1=\$3&ys_ms_sef=y&tab_block=NEW",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/([^/]*)/?letter-([^/]{1,3})/(.*)#",
		"RULE" => "SECTION_CODE=\$1&letter=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/bestseller/sort-(.*[^-])-(.*)/(.*)#",
		"RULE" => "\$3&order=\$1&by=\$2&ys_ms_sef=y&tab_block=BESTSELLER",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/page_count-([0-9]+)/#",
		"RULE" => "SECTION_CODE=\$1&page_count=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/sort-(.*[^-])-(.*)/#",
		"RULE" => "SECTION_CODE=\$1&order=\$2&by=\$3",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/computers-and-laptops/tablet-pc/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/computers-and-laptops/tablet-pc/index.php",
	),
	array(
		"CONDITION" => "#^/bestseller/sort-(.*[^-])-(.*)/#",
		"RULE" => "order=\$1&by=\$2",
		"ID" => "",
		"PATH" => "/bestseller/index.php",
	),
	array(
		"CONDITION" => "#^/bestseller/page-([0-9]+)/(.*)#",
		"RULE" => "\$2&PAGEN_1=\$1&ys_ms_sef=y&tab_block=BESTSELLER",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/sale/sort-(.*[^-])-(.*)/(.*)#",
		"RULE" => "\$3&order=\$1&by=\$2&ys_ms_sef=y&tab_block=SALE",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/page-([0-9]+)/#",
		"RULE" => "SECTION_CODE=\$1&PAGEN_1=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/hit/sort-(.*[^-])-(.*)/(.*)#",
		"RULE" => "\$3&order=\$1&by=\$2&ys_ms_sef=y&tab_block=HIT",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/new/sort-(.*[^-])-(.*)/(.*)#",
		"RULE" => "\$3&order=\$1&by=\$2&ys_ms_sef=y&tab_block=NEW",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/buyers/tips-pediatricians/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/buyers/tips-pediatricians/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/(.*).html(.*)#",
		"RULE" => "SECTION_CODE=\$1&ELEMENT_CODE=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.+)/(.+).html(.*)",
		"RULE" => "SECTION_CODE=\$1&ELEMENT_CODE=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/compare/(.*)/(.*)#",
		"RULE" => "action=COMPARE&compareQuery=\$1",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/sale/sort-(.*[^-])-(.*)/#",
		"RULE" => "order=\$1&by=\$2",
		"ID" => "",
		"PATH" => "/sale/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/#",
		"RULE" => "SECTION_CODE=\$1&view=\$2",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/buyers/sign-for-tesing/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/buyers/sign-for-tesing/index.php",
	),
	array(
		"CONDITION" => "#^/sale/page-([0-9]+)/(.*)#",
		"RULE" => "\$2&PAGEN_1=\$1&ys_ms_sef=y&tab_block=SALE",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/new/sort-(.*[^-])-(.*)/#",
		"RULE" => "order=\$1&by=\$2",
		"ID" => "",
		"PATH" => "/new/index.php",
	),
	array(
		"CONDITION" => "#^/hit/sort-(.*[^-])-(.*)/#",
		"RULE" => "order=\$1&by=\$2",
		"ID" => "",
		"PATH" => "/hit/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/(\\?(.*))?#",
		"RULE" => "SECTION_CODE=\$1&\$3",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/new/page-([0-9]+)/(.*)#",
		"RULE" => "\$2&PAGEN_1=\$1&ys_ms_sef=y&tab_block=NEW",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/hit/page-([0-9]+)/(.*)#",
		"RULE" => "\$2&PAGEN_1=\$1&ys_ms_sef=y&tab_block=HIT",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.+)/(.+)#",
		"RULE" => "SECTION_CODE=\$1",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/personal/lists/#",
		"RULE" => "",
		"ID" => "bitrix:lists",
		"PATH" => "/personal/lists/index.php",
	),
	array(
		"CONDITION" => "#^/bestseller/(.*)#",
		"RULE" => "\$1&ys_ms_sef=y&tab_block=BESTSELLER",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.+)/#",
		"RULE" => "SECTION_CODE=\$1",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/campaigns/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/campaigns/index.php",
	),
	array(
		"CONDITION" => "#^/sale/(.*)#",
		"RULE" => "\$1&ys_ms_sef=y&tab_block=SALE",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/new/(.*)#",
		"RULE" => "\$1&ys_ms_sef=y&tab_block=NEW",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/hit/(.*)#",
		"RULE" => "\$1&ys_ms_sef=y&tab_block=HIT",
		"ID" => "yenisite:main_spec",
		"PATH" => "/yenisite.main_spec/index.php",
	),
	array(
		"CONDITION" => "#^/brands/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/brands/index.php",
	),
	array(
		"CONDITION" => "#^/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/news/index.php",
	),
);

?>