<?
$arUrlRewrite = array(
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/letter-([^/]{1,3})/page-([0-9]+)/(.*)#",
		"RULE"  =>  "SECTION_CODE=$1&order=$3&by=$4&view=$2&page_count=$5&letter=$6&PAGEN_1=$7",
		"ID"    =>  "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?view-(\\w*)/sort-(\\w*)-(\\w*)/letter-([^/]{1,3})/page-([0-9]+)/(.*)#",
		"RULE"  =>  "SECTION_CODE=$1&order=$3&by=$4&view=$2&letter=$5&PAGEN_1=$6",
		"ID"    =>  "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/letter-([^/]{1,3})/(.*)#",
		"RULE"  =>  "SECTION_CODE=$1&order=$3&by=$4&view=$2&page_count=$5&letter=$6",
		"ID"    =>  "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?letter-([^/]{1,3})/page_count-([0-9]+)/(.*)#",
		"RULE" 	=> "SECTION_CODE=$1&letter=$2&page_count=$3",
		"ID" 	=> "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?page_count-([0-9]+)/letter-([^/]{1,3})/(.*)#",
		"RULE" 	=> "SECTION_CODE=$1&page_count=$2&letter=$3",
		"ID" 	=> "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?letter-([^/]{1,3})/page-([0-9]+)/(.*)#",
		"RULE" 	=> "SECTION_CODE=$1&letter=$2&PAGEN_1=$3",
		"ID" 	=> "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/catalog/([^/]*)/?letter-([^/]{1,3})/(.*)#",
		"RULE" 	=> "SECTION_CODE=$1&letter=$2",
		"ID" 	=> "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/page-([0-9]+)/#",
		"RULE" => "SECTION_CODE=$1&order=$3&by=$4&view=$2&PAGEN_1=$6&page_count=$5",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/page-([0-9]+)/#",
		"RULE" => "SECTION_CODE=$1&order=$3&by=$4&view=$2&PAGEN_1=$5",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/page_count-([0-9]+)/#",
		"RULE" => "SECTION_CODE=$1&order=$3&by=$4&view=$2&page_count=$5",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/sort-(\\w*)-(\\w*)/#",
		"RULE" => "SECTION_CODE=$1&order=$3&by=$4&view=$2",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/page-([0-9]+)/#",
		"RULE" => "SECTION_CODE=$1&PAGEN_1=$2",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/page_count-([0-9]+)/#",
		"RULE" => "SECTION_CODE=$1&page_count=$2",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/sort-(.*[^-])-(.*)/#",
		"RULE" => "SECTION_CODE=$1&order=$2&by=$3",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/view-(\\w*)/#",
		"RULE" => "SECTION_CODE=$1&view=$2",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/(.*).html(.*)#",
		"RULE" => "SECTION_CODE=$1&ELEMENT_CODE=$2",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/compare/(.*)/(.*)#",
		"RULE" => "action=COMPARE&compareQuery=\$1",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/(.*)/(\\?(.*))?#",
		"RULE" => "SECTION_CODE=\$1&\$3",
		"ID" => "",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "#SITE_DIR#catalog/index.php",
	),
	array(
		"CONDITION" =>  "#^/hit/sort-(.*[^-])-(.*)/#",
		"RULE"  =>  "order=$1&by=$2",
		"ID"    =>  "",
		"PATH"  =>  "#SITE_DIR#hit/index.php",
	),
	array(
		"CONDITION" =>  "#^/new/sort-(.*[^-])-(.*)/#",
		"RULE"  =>  "order=$1&by=$2",
		"ID"    =>  "",
		"PATH"  =>  "#SITE_DIR#new/index.php",
	),
	array(
		"CONDITION" =>  "#^/sale/sort-(.*[^-])-(.*)/#",
		"RULE"  =>  "order=$1&by=$2",
		"ID"    =>  "",
		"PATH"  =>  "#SITE_DIR#sale/index.php",
	),
	array(
		"CONDITION" =>  "#^/bestseller/sort-(.*[^-])-(.*)/#",
		"RULE"  =>  "order=$1&by=$2",
		"ID"    =>  "",
		"PATH"  =>  "#SITE_DIR#bestseller/index.php",
	),
	array(
		"CONDITION"	=>	"#^/personal/lists/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:lists",
		"PATH"	=>	"#SITE_DIR#personal/lists/index.php",
	),	
	array(
		"CONDITION"	=>	"#^/campaigns/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"#SITE_DIR#campaigns/index.php",
	),
	array(
		"CONDITION"	=>	"#^/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"#SITE_DIR#news/index.php",
	),
);
?>