ALTER TABLE `ys_geoip_store_items`
ADD COLUMN `META_TITLE` VARCHAR(200) NULL AFTER `DEFAULT`,
ADD COLUMN `META_KEYWORDS` VARCHAR(200) NULL AFTER `META_TITLE`,
ADD COLUMN `META_DESCRIPTION` VARCHAR(200) NULL AFTER `META_KEYWORDS`;