<?
$arTooltips = array(
	"SETTINGS_HIDE" => GetMessage("SETTINGS_HIDE_TIP"),
	"FOR_ORDER_DESCRIPTION" => GetMessage("FOR_ORDER_DESCRIPTION_TIP"),

	"RESIZER_BOX" => GetMessage("RESIZER_BOX_TIP"),
	
	"COMPLETE_SET_PROPERTIES" => GetMessage("COMPLETE_SET_PROPERTIES_TIP"),
	
	"PRODUCT_DISPLAY_MODE" => GetMessage("PRODUCT_DISPLAY_MODE_TIP"),
);
?>