CREATE TABLE IF NOT EXISTS `ys_geoip_store_items` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(200) NOT NULL,
	`LOCATION_ID_DELIVERY` INT(10) UNSIGNED NOT NULL,
	`DOMAIN_NAME` VARCHAR(200) NOT NULL,
	`GROUP_ID` INT(10) UNSIGNED,
	`SITE_ID` VARCHAR(10),
	`META_TITLE` VARCHAR(200),
	`META_KEYWORDS` VARCHAR(200),
	`META_DESCRIPTION` VARCHAR(200),
	`DEFAULT` CHAR(1),
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ys_geoip_store_places` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ITEM_ID` INT(10) UNSIGNED NOT NULL,
	`LOCATION_ID_STATISTIC` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ys_geoip_store_price_types` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`PRICE_ID` INT(10) UNSIGNED NOT NULL,
	`PRICE_CODE` VARCHAR(50) NOT NULL,
	`ITEM_ID` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ys_geoip_store_stores` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`STORE_ID` INT(10) UNSIGNED NOT NULL,
	`ITEM_ID` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ys_geoip_store_currency2country` (
	`COUNTRY_ID` char(2) NOT NULL,
	`CURRENCY_ID` char(3) NOT NULL,
	PRIMARY KEY (`COUNTRY_ID`, `CURRENCY_ID`)
);

INSERT INTO `ys_geoip_store_currency2country` (`COUNTRY_ID`, `CURRENCY_ID`)
VALUES ('RU', 'RUB'),
('US', 'USD'),
('UA', 'UAH'),
('GB', 'EUR'),
('FR', 'EUR'),
('DE', 'EUR'),
('BY', 'BYR');