<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Admin Forum");
?><?$APPLICATION->IncludeComponent("bitrix:forum", ".default", array(
	"THEME" => "fluxbb",
	"SHOW_TAGS" => "Y",
	"SHOW_AUTH_FORM" => "Y",
	"TMPLT_SHOW_ADDITIONAL_MARKER" => "",
	"RESTART" => "N",
	"NO_WORD_LOGIC" => "N",
	"USE_LIGHT_VIEW" => "Y",
	"FID" => array(
	),
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/admin-forum/",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"CACHE_TIME_USER_STAT" => "60",
	"CACHE_TIME_FOR_FORUM_STAT" => "3600",
	"FORUMS_PER_PAGE" => "100",
	"TOPICS_PER_PAGE" => "100",
	"MESSAGES_PER_PAGE" => "100",
	"IMAGE_SIZE" => "500",
	"ATTACH_MODE" => array(
		0 => "THUMB",
		1 => "NAME",
	),
	"ATTACH_SIZE" => "500",
	"SET_TITLE" => "Y",
	"USE_RSS" => "Y",
	"RSS_COUNT" => "30",
	"SHOW_VOTE" => "N",
	"SHOW_RATING" => "",
	"RATING_ID" => array(
	),
	"RATING_TYPE" => "",
	"SEO_USER" => "N",
	"SEO_USE_AN_EXTERNAL_SERVICE" => "Y",
	"SHOW_FORUM_USERS" => "Y",
	"SHOW_SUBSCRIBE_LINK" => "N",
	"SHOW_NAVIGATION" => "Y",
	"SHOW_LEGEND" => "Y",
	"SHOW_STATISTIC_BLOCK" => array(
		0 => "STATISTIC",
		1 => "BIRTHDAY",
		2 => "USERS_ONLINE",
	),
	"SHOW_FORUMS" => "Y",
	"SHOW_FIRST_POST" => "N",
	"SHOW_AUTHOR_COLUMN" => "N",
	"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
	"PAGE_NAVIGATION_TEMPLATE" => "forum",
	"PAGE_NAVIGATION_WINDOW" => "5",
	"AJAX_POST" => "N",
	"WORD_WRAP_CUT" => "23",
	"WORD_LENGTH" => "50",
	"USER_PROPERTY" => array(
	),
	"USER_FIELDS" => array(
	),
	"HELP_CONTENT" => "",
	"RULES_CONTENT" => "",
	"CHECK_CORRECT_TEMPLATES" => "Y",
	"RSS_CACHE" => "1800",
	"PATH_TO_AUTH_FORM" => "",
	"TIME_INTERVAL_FOR_USER_STAT" => "10",
	"DATE_FORMAT" => "d.m.Y",
	"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
	"USE_NAME_TEMPLATE" => "N",
	"NAME_TEMPLATE" => "",
	"EDITOR_CODE_DEFAULT" => "N",
	"SEND_MAIL" => "E",
	"SEND_ICQ" => "A",
	"SET_NAVIGATION" => "Y",
	"SET_DESCRIPTION" => "Y",
	"SET_PAGE_PROPERTY" => "Y",
	"SHOW_FORUM_ANOTHER_SITE" => "Y",
	"RSS_TYPE_RANGE" => array(
		0 => "RSS2",
	),
	"RSS_TN_TITLE" => "",
	"RSS_TN_DESCRIPTION" => "",
	"SEF_URL_TEMPLATES" => array(
		"index" => "index.php",
		"list" => "forum#FID#/",
		"read" => "forum#FID#/topic#TID#/",
		"message" => "messages/forum#FID#/topic#TID#/message#MID#/",
		"help" => "help/",
		"rules" => "rules/",
		"message_appr" => "messages/approve/forum#FID#/topic#TID#/",
		"message_move" => "messages/move/forum#FID#/topic#TID#/message#MID#/",
		"rss" => "rss/#TYPE#/#MODE#/#IID#/",
		"search" => "search/",
		"subscr_list" => "subscribe/",
		"active" => "topic/new/",
		"topic_move" => "topic/move/forum#FID#/topic#TID#/",
		"topic_new" => "topic/add/forum#FID#/",
		"topic_search" => "topic/search/",
		"user_list" => "users/",
		"profile" => "user/#UID#/edit/",
		"profile_view" => "user/#UID#/",
		"user_post" => "user/#UID#/post/#mode#/",
		"message_send" => "user/#UID#/send/#TYPE#/",
		"pm_list" => "pm/folder#FID#/",
		"pm_edit" => "pm/folder#FID#/message#MID#/user#UID#/#mode#/",
		"pm_read" => "pm/folder#FID#/message#MID#/",
		"pm_search" => "pm/search/",
		"pm_folder" => "pm/folders/",
	)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>